env:
  global:
    - secure: h1fCXc70Ye3uJ9qe2GVY5uosI1y1BLMd/mhikGbTtMsBQXEVQJ+A1WS1quck8imIOFQd8A04qOs/FseUDzZtxLEfbq0BYuThfTq5+I6ktjLQGPIBvRm5tGmdP6j0QaLq7j3SYAEyvuPhfRQ/puboqE0+LgBXTj7GI7fRQ8KI9FFGwBPjU3WKnQOY1Hi2vnJNQmD6tcJgi8g/QFdOtujpB7QqsrzTU/EcRli86gYVlezJ/byAHhc+X5Re5XIQVHsPEBon8MFb4AvmdjSXMkW6sHbFsZV9Eliy37oHE1/33rwvf0AqPtgYYicwFdMk79IpyZjxVjBiGIfqdUpgnsyvEyf5UFZvsPr4XdjEiQC27YZzkK3Sdk4zl5AllqLIe/GrT1Jk7B20jOMOF9jbeUoQJgf0J0Bt1PP9xW1i+mUTaUzgM2M+URY3cvGoKK366LtBa40j1Haj4Kq3EPiEpO73iu+itZCpW1/f9O9YN6YyFPaT73TZ+eZREQhIQBXv5rep9LvulmZu8X+VpOD/PcDefEFAAWeDQWVg7jYLUjj2WCMX6UF5H+8N9fgXyoyYQaIs1aG2lFA0RlEJe3ncfkyHitwIm+sXh/pW+oU7BztveCXNSlwJF/IBF733K3gqp+ZxwwkYmsw7VXPCtQeCpC9XUDB85KSbdkrVa6xC6041mkw=
sudo: true
language: rust
rust: stable
script:
  - cargo build
  - cargo doc
after_script:
  - mv target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
